name: publish

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew assemble --no-daemon
      - name: Publish
        run: ./gradlew publishPlugins -Pgradle.publish.key=${{KEY}} -Pgradle.publish.secret=${{SECRET}}
        env:
          KEY: ${{ secrets.KEY }}
          SECRET: ${{ secrets.SECRET }}